export const ProductImage = "https://via.placeholder.com/200x200?text=Product";

// 차량 부품 카테고리
export const CATEGORIES = [
  { name: "엔진 부품", icon: "🔧" },
  { name: "제동 장치", icon: "🛑" },
  { name: "조향 및 현가 장치", icon: "🔩" },
  { name: "전기 및 전자 부품", icon: "⚡" },
  { name: "외장 및 차체 부품", icon: "🚗" },
  { name: "내장 및 시트", icon: "💺" },
  { name: "냉각 및 공조 시스템", icon: "❄️" },
  { name: "구동 및 변속 부품", icon: "⚙️" },
  { name: "배기 및 흡기 시스템", icon: "💨" },
  { name: "소모품 및 오일류", icon: "🛢️" },
];

export const SUBCATEGORIES = {
  "엔진 부품": [
    { name: "피스톤 / 피스톤링", image: "Piston" },
    { name: "크랭크샤프트", image: "Crankshaft" },
    { name: "캠샤프트", image: "Camshaft" },
    { name: "실린더 헤드 가스켓", image: "Gasket" },
    { name: "타이밍 벨트 / 체인", image: "TimingBelt" },
    { name: "오일팬", image: "OilPan" },
    { name: "엔진 마운트", image: "EngineMount" },
    { name: "인젝터 / 연료 펌프", image: "Injector" },
  ],
  "제동 장치": [
    { name: "브레이크 패드", image: "BrakePad" },
    { name: "브레이크 디스크(로터)", image: "BrakeDisc" },
    { name: "브레이크 캘리퍼", image: "Caliper" },
    { name: "브레이크 호스 / 라인", image: "BrakeHose" },
    { name: "브레이크 마스터 실린더", image: "MasterCylinder" },
    { name: "주차 브레이크 케이블", image: "ParkingBrake" },
    { name: "ABS 센서", image: "ABSSensor" },
    { name: "브레이크 액(DOT4)", image: "BrakeFluid" },
  ],
  "조향 및 현가 장치": [
    { name: "쇼크 업소버(댐퍼)", image: "ShockAbsorber" },
    { name: "코일 스프링", image: "CoilSpring" },
    { name: "스태빌라이저 링크", image: "StabilizerLink" },
    { name: "볼 조인트", image: "BallJoint" },
    { name: "타이로드 엔드", image: "TieRod" },
    { name: "파워 스티어링 펌프", image: "SteeringPump" },
    { name: "스티어링 랙 & 피니언", image: "SteeringRack" },
    { name: "허브 베어링", image: "HubBearing" },
  ],
  "전기 및 전자 부품": [
    { name: "배터리", image: "Battery" },
    { name: "알터네이터(발전기)", image: "Alternator" },
    { name: "스타터 모터", image: "StarterMotor" },
    { name: "점화 코일 / 플러그", image: "IgnitionCoil" },
    { name: "ECU / 센서류", image: "ECU" },
    { name: "퓨즈 & 릴레이", image: "Fuse" },
    { name: "전조등 / 후미등", image: "Headlight" },
    { name: "와이퍼 모터", image: "WiperMotor" },
  ],
  "외장 및 차체 부품": [
    { name: "범퍼(전/후)", image: "Bumper" },
    { name: "펜더", image: "Fender" },
    { name: "후드(보닛)", image: "Hood" },
    { name: "도어 패널", image: "DoorPanel" },
    { name: "사이드 미러", image: "SideMirror" },
    { name: "앞 / 뒤 유리(윈드실드)", image: "Windshield" },
    { name: "루프 패널", image: "RoofPanel" },
    { name: "몰딩 / 가니쉬", image: "Molding" },
  ],
  "내장 및 시트": [
    { name: "운전석 / 조수석 시트", image: "Seat" },
    { name: "대시보드", image: "Dashboard" },
    { name: "센터 콘솔", image: "Console" },
    { name: "도어 트림", image: "DoorTrim" },
    { name: "헤드라이너", image: "Headliner" },
    { name: "카펫 / 매트", image: "Carpet" },
    { name: "스티어링 휠", image: "SteeringWheel" },
    { name: "에어백 모듈", image: "Airbag" },
  ],
  "냉각 및 공조 시스템": [
    { name: "라디에이터", image: "Radiator" },
    { name: "냉각수 호스", image: "CoolantHose" },
    { name: "써모스탯", image: "Thermostat" },
    { name: "워터 펌프", image: "WaterPump" },
    { name: "냉각팬 / 팬 클러치", image: "CoolingFan" },
    { name: "A/C 컴프레서", image: "ACCompressor" },
    { name: "콘덴서", image: "Condenser" },
    { name: "에바포레이터", image: "Evaporator" },
  ],
  "구동 및 변속 부품": [
    { name: "클러치 킷(디스크/커버)", image: "Clutch" },
    { name: "드라이브 샤프트(CV조인트)", image: "DriveShaft" },
    { name: "트랜스미션 필터", image: "TransmissionFilter" },
    { name: "ATF / MTF 오일", image: "TransmissionOil" },
    { name: "토크 컨버터", image: "TorqueConverter" },
    { name: "디퍼렌셜(차동장치)", image: "Differential" },
    { name: "프로펠러 샤프트", image: "PropShaft" },
    { name: "기어 박스", image: "GearBox" },
  ],
  "배기 및 흡기 시스템": [
    { name: "에어 필터", image: "AirFilter" },
    { name: "인테이크 매니폴드", image: "IntakeManifold" },
    { name: "터보차저", image: "Turbocharger" },
    { name: "인터쿨러", image: "Intercooler" },
    { name: "배기 매니폴드", image: "ExhaustManifold" },
    { name: "촉매 변환기(캐탈리스트)", image: "Catalyst" },
    { name: "머플러", image: "Muffler" },
    { name: "산소 센서(람다 센서)", image: "O2Sensor" },
  ],
  "소모품 및 오일류": [
    { name: "엔진 오일", image: "EngineOil" },
    { name: "오일 필터", image: "OilFilter" },
    { name: "에어컨 필터(캐빈 필터)", image: "CabinFilter" },
    { name: "연료 필터", image: "FuelFilter" },
    { name: "스파크 플러그", image: "SparkPlug" },
    { name: "냉각수", image: "Coolant" },
    { name: "와이퍼 블레이드", image: "WiperBlade" },
    { name: "타이어 / 휠", image: "Tyre" },
  ],
  기본: [
    { name: "베스트셀러", image: "Best" },
    { name: "신제품", image: "New" },
    { name: "기획전", image: "Deal" },
    { name: "추천", image: "Pick" },
  ],
};
