import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import SideBar from "@/components/sideBar";
import type { Metadata } from "next";
import styles from "./layout.module.css";

import "./globals.css";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <Header />
        <SideBar />
        <main className={styles.main}>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
